#!/bin/bash

if [ $# -ne 1 ]; then
  echo "Usage: postCast <host>"
  exit 1
fi

if ! type gst-launch-0.10 &>/dev/null; then
  echo "You need to install gstreamer0.10-tools"
  exit 1
fi

if ! type netcat &>/dev/null; then
  echo "You need to install netcat"
  exit 1
fi

HOST="$1"
{ 
  cat<<EOHEADER
POST /cgi-bin/uploadstream HTTP/1.1
User-Agent: postCast
Host: $HOST
Accept: text/html, application/xml;q=0.9, application/xhtml+xml, image/png, image/webp, image/jpeg, image/gif, image/x-xbitmap, */*;q=0.1
Accept-Language: en-US,en;q=0.9
Accept-Encoding: gzip, deflate
Referer: http://$HOST/
Connection: Keep-Alive
Content-Length: 4294967296
Content-Type: multipart/form-data; boundary=----------mSW1oHw5brtEe0jxj0284x

------------mSW1oHw5brtEe0jxj0284x
Content-Disposition: form-data; name="Datei"; filename="screencast.mp4"
Content-Type: video/avi

EOHEADER
  MONITOR="`pactl list | grep -Po 'Monitor Source: \K(.*)(?=)'`"
  gst-launch-0.10 pulsesrc device="$MONITOR" ! ffenc_ac3 ! mpegtsmux ! fdsink
} | netcat $HOST 80 1>/dev/null

