#!/bin/bash

if [ $# -ne 1 ]; then
  echo "Usage: postDisplay <host>"
  exit 1
fi

if ! type import &>/dev/null; then
  echo "You need to install ImageMagick"
  exit 1
fi

if ! type netcat &>/dev/null; then
  echo "You need to install netcat"
  exit 1
fi

HOST="$1"
{ 
  TMP="`mktemp`"
  import "PNG:$TMP"
	SIZE="`stat -c %s "$TMP"`"

  cat<<EOHEADER
POST /cgi-bin/uploadstream HTTP/1.1
User-Agent: postDisplay
Host: $HOST
Accept: text/html, application/xml;q=0.9, application/xhtml+xml, image/png, image/webp, image/jpeg, image/gif, image/x-xbitmap, */*;q=0.1
Accept-Language: en-US,en;q=0.9
Accept-Encoding: gzip, deflate
Referer: http://10.20.30.51/
Connection: Keep-Alive
Content-Length: $SIZE
Content-Type: multipart/form-data; boundary=----------mSW1oHw5brtEe0jxj0284x

------------mSW1oHw5brtEe0jxj0284x
Content-Disposition: form-data; name="Datei"; filename="screenshot.png"
Content-Type: image/png

EOHEADER
  cat "$TMP"
  rm "$TMP"
} | netcat $HOST 80 1>/dev/null

